spcup22:
  raw_audio:
    training:
      part1:
        link: https://www.dropbox.com/s/36yqmymkva2bwdi/spcup_2022_training_part1.zip?dl=1
        filename: spcup_2022_training_part1.zip
        default_path: data/spcup22/training/part1/spcup_2022_training_part1
      part2:
        link: https://www.dropbox.com/s/wsmlthhri29fb79/spcup_2022_unseen.zip?dl=1
        filename: spcup_2022_unseen.zip
        default_path: data/spcup22/training/part2/spcup_2022_unseen
    evaluation:
      part1:
        link: https://www.dropbox.com/s/ftkyvwxgr9wl7jf/spcup_2022_eval_part1.zip?dl=1
        filename: spcup_2022_eval_part1.zip
        default_path: data/spcup22/evaluation/part1/spcup_2022_eval_part1
      part2:
        link: https://www.dropbox.com/s/zylz07o2z0x308g/spcup_2022_eval_part2.zip?dl=1
        filename: spcup_2022_eval_part2.zip
        default_path: data/spcup22/evaluation/part2/spcup_2022_eval_part2
