spcup22:
  mel_feature:
    training:
      not_augmented:
        link: https://www.dropbox.com/s/9nkc8eyu5lfendp/spcup_2022_training.zip?dl=1
        filename: spcup_2022_training.zip
        default_path: training
      augmented:
        link: https://www.dropbox.com/s/e0l2j30cxy6ngn6/spcup_2022_train_augmented.zip?dl=1
        filename: spcup_2022_train_augmented.zip
        default_path: training_augmented
    evaluation:
      evaluation_part1:
        link: https://www.dropbox.com/s/d1kob8d11ynrv8m/spcup_2022_eval_part1_mel_features.zip?dl=1
        filename: spcup_2022_eval_part1_mel_features.zip
        default_path: evaluation_part1
      evaluation_part2:
        link: https://www.dropbox.com/s/24qr0gvwwmfj0rd/spcup_2022_eval_part2_mel_features.zip?dl=1
        filename: spcup_2022_eval_part2_mel_features.zip
        default_path: evaluation_part2
