tssdnet:
  training:
    batch_size: 128
    learning_rate: 1.0e-3
    exp_lr_scheduler_gamma: 0.95
    save_checkpoint_epoch_interval: 1
  wandb:
    project: spcup22
    entity: mahieyin-rahmun

svm:
  features:
    n_mfcc: 40
    hop_length: 256
  params:
    loss: modified_huber
    penalty: l2
    alpha: 1.0e-3
    verbose: 0
    random_state: 42
    n_jobs: 8
  training:
    batch_size: 240
    epochs: 200

gmm:
  features:
    n_mfcc: 40
    hop_length: 256
  training:
    batch_size: 240
    epochs: 200

cnn:
  training:
    batch_size: 64
    learning_rate: 1.0e-3
    lr_scheduler_factor: 0.5
    lr_scheduler_patience: 10
    save_checkpoint_epoch_interval: 5
    check_val_every_n_epoch: 1
