function [audioAug] = noise_inject(audioIn, fs, noise_probability, SNR_value)
    if nargin < 3
        noise_probability = 1;
        SNR_value = 20;
    end

    augmenter = audioDataAugmenter( ...
        "AugmentationParameterSource","specify", ...
        "AddNoiseProbability", noise_probability, ...
        "SNR", SNR_value, ...
        "ApplyTimeStretch", false,...
        "ApplyVolumeControl", false, ...
        "ApplyPitchShift", false, ...
        "ApplyTimeStretch", false, ...
        "ApplyTimeShift", false);
    
    data = augment(augmenter, audioIn, fs);
    audioAug = data.Audio{1};
end

